In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\paula\Desktop\Sejong Data project\외국인\오류 퍼센트_태국어제외\일어\통합 일어 오류유형_수정.xlsx")
df

,JP QB,발음오류,빈도,Unnamed: 3,JP QC,발음오류.1,빈도.1,Unnamed: 7,JP RB,발음오류.2,빈도.2,Unnamed: 11,JP RC,발음오류.3,빈도.3
0,0.0,C1,203.0,NaN,0.0,C1,550.0,NaN,0.0,C1,235.0,NaN,0,C,2
1,1.0,C2,34.0,NaN,1.0,C2,73.0,NaN,1.0,C2,39.0,NaN,1,C1,913
2,2.0,C3,1.0,NaN,2.0,C3,3.0,NaN,2.0,C4,1441.0,NaN,2,C2,178
3,3.0,C4,848.0,NaN,3.0,C4,3058.0,NaN,3.0,C5,308.0,NaN,3,C3,22
4,4.0,C5,105.0,NaN,4.0,C5,538.0,NaN,4.0,C6,34.0,NaN,4,C4,6781
5,5.0,C6,26.0,NaN,5.0,C6,94.0,NaN,5.0,F,55.0,NaN,5,C5,1102
6,6.0,CI,14.0,NaN,6.0,C7,3.0,NaN,6.0,I,6.0,NaN,6,C6,234
7,7.0,F,41.0,NaN,7.0,CI,25.0,NaN,7.0,L,19.0,NaN,7,C6E,1
8,8.0,I,4.0,NaN,8.0,F,178.0,NaN,8.0,N1,425.0,NaN,8,C7,18
9,9.0,L,125.0,NaN,9.0,I,10.0,NaN,9.0,N2,242.0,NaN,9,C7E,2
10,10.0,N1,332.0,NaN,10.0,L,305.0,NaN,10.0,O1,462.0,NaN,10,F,264
11,11.0,N2,67.0,NaN,11.0,N1,1090.0,NaN,11.0,O2,124.0,NaN,11,I,137
12,12.0,O1,403.0,NaN,12.0,N2,245.0,NaN,12.0,O3,18.0,NaN,12,L,246
13,13.0,O2,93.0,NaN,13.0,O1,1748.0,NaN,13.0,O4,38.0,NaN,13,N1,2740
14,14.0,O3,15.0,NaN,14.0,O2,382.0,NaN,14.0,O5,28.0,NaN,14,N2,560
15,15.0,O4,23.0,NaN,15.0,O3,47.0,NaN,15.0,O6,8.0,NaN,15,O,1
16,16.0,O5,21.0,NaN,16.0,O4,64.0,NaN,16.0,O7,4.0,NaN,16,O1,3180
17,17.0,O6,21.0,NaN,17.0,O5,77.0,NaN,17.0,P,53.0,NaN,17,O2,1615
18,18.0,O7,7.0,NaN,18.0,O6,32.0,NaN,18.0,R1,19.0,NaN,18,O3,105
19,19.0,OI,4.0,NaN,19.0,O7,40.0,NaN,19.0,R1E,3.0,NaN,19,O4,238
20,20.0,P,57.0,NaN,20.0,OI,16.0,NaN,20.0,R1O,1.0,NaN,20,O5,117
21,21.0,R1,32.0,NaN,21.0,P,252.0,NaN,21.0,R2,35.0,NaN,21,O6,110
22,22.0,R1E,5.0,NaN,22.0,R1,92.0,NaN,22.0,R2E,74.0,NaN,22,O7,36
23,23.0,R1O,2.0,NaN,23.0,R1E,5.0,NaN,23.0,R3,157.0,NaN,23,P,352
24,24.0,R2,16.0,NaN,24.0,R1O,19.0,NaN,24.0,R3E,8.0,NaN,24,R,2
25,25.0,R2E,142.0,NaN,25.0,R2,42.0,NaN,25.0,R3O,3.0,NaN,25,R1,272
26,26.0,R2O,5.0,NaN,26.0,R2E,376.0,NaN,26.0,R4,1.0,NaN,26,R1E,37
27,27.0,R3,56.0,NaN,27.0,R3,134.0,NaN,27.0,R4E,2.0,NaN,27,R1O,18
28,28.0,R3E,8.0,NaN,28.0,R3E,25.0,NaN,28.0,R5,24.0,NaN,28,R2,152
29,29.0,R3O,10.0,NaN,29.0,R3O,3.0,NaN,29.0,R5E,8.0,NaN,29,R2E,816
30,30.0,R4E,3.0,NaN,30.0,R4E,74.0,NaN,30.0,R6,37.0,NaN,30,R2O,31
31,31.0,R5,14.0,NaN,31.0,R4O,1.0,NaN,31.0,R7,36.0,NaN,31,R3,591
32,32.0,R5E,16.0,NaN,32.0,R5,36.0,NaN,32.0,S,475.0,NaN,32,R3E,116
33,33.0,R6,15.0,NaN,33.0,R5E,36.0,NaN,NaN,NaN,NaN,NaN,33,R3O,112
34,34.0,R7,1.0,NaN,34.0,R6,33.0,NaN,NaN,NaN,NaN,NaN,34,R4,1
35,35.0,R8,1.0,NaN,35.0,R6E,1.0,NaN,NaN,NaN,NaN,NaN,35,R4E,37
36,36.0,R8O,2.0,NaN,36.0,R7,45.0,NaN,NaN,NaN,NaN,NaN,36,R4O,1
37,37.0,S,242.0,NaN,37.0,R7E,5.0,NaN,NaN,NaN,NaN,NaN,37,R5,57
38,NaN,NaN,NaN,NaN,38.0,R8,8.0,NaN,NaN,NaN,NaN,NaN,38,R5E,13
39,NaN,NaN,NaN,NaN,39.0,R8E,1.0,NaN,NaN,NaN,NaN,NaN,39,R6,574
40,NaN,NaN,NaN,NaN,40.0,S,956.0,NaN,NaN,NaN,NaN,NaN,40,R6E,3
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41,R6O,2
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42,R7,50
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43,R7O,2
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44,R8,14
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,R8E,15
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46,R8O,8
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47,S,2410

In [8]:
# Select the columns containing error types and frequencies
error_columns = [col for col in df.columns if '발음오류' in col]
frequency_columns = [col for col in df.columns if '빈도' in col]

# Get the corresponding error and frequency columns in pairs
column_pairs = zip(error_columns, frequency_columns)

# Create an empty DataFrame to store the stacked data
stacked_df = pd.DataFrame(columns=['발음오류', '빈도'])

# Stack the columns and populate the stacked DataFrame
for error_col, frequency_col in column_pairs:
    stacked = df[[error_col, frequency_col]].dropna().rename(columns={error_col: '발음오류', frequency_col: '빈도'})
    stacked_df = pd.concat([stacked_df, stacked], ignore_index=True)

# Group the DataFrame by error types and calculate the sum of frequencies
grouped_df = stacked_df.groupby('발음오류')['빈도'].sum().reset_index()

# Calculate the total sum of frequencies
total_sum = grouped_df['빈도'].sum()

# Calculate the percentage for each error type
grouped_df['Percentage'] = (grouped_df['빈도'] / total_sum) * 100
grouped_df = grouped_df.sort_values(by ='Percentage', ascending = False)

# Print the updated DataFrame
print(grouped_df)

   발음오류       빈도  Percentage
4    C4  12128.0   28.572775
17   O1   5793.0   13.647929
14   N1   4587.0   10.806672
50    S   4083.0    9.619281
18   O2   2214.0    5.216039
5    C5   2053.0    4.836734
1    C1   1901.0    4.478632
31  R2E   1408.0    3.317156
15   N2   1114.0    2.624511
33   R3    938.0    2.209867
25    P    714.0    1.682137
13    L    695.0    1.637375
41   R6    659.0    1.552561
11    F    538.0    1.267493
27   R1    415.0    0.977713
6    C6    388.0    0.914103
20   O4    363.0    0.855204
2    C2    324.0    0.763323
30   R2    245.0    0.577204
21   O5    243.0    0.572492
19   O3    185.0    0.435848
22   O6    171.0    0.402865
34  R3E    157.0    0.369882
12    I    157.0    0.369882
44   R7    132.0    0.310983
39   R5    131.0    0.308627
35  R3O    128.0    0.301560
37  R4E    116.0    0.273288
23   O7     87.0    0.204966
40  R5E     73.0    0.171983
28  R1E     50.0    0.117797
29  R1O     40.0    0.094237
10   CI     39.0    0.091881
32  R2O     36.0    0.084814
3    C3     26.0    0.061254
47   R8     23.0    0.054186
8    C7     21.0    0.049475
24   OI     20.0    0.047119
48  R8E     16.0    0.037695
49  R8O     10.0    0.023559
45  R7E      5.0    0.011780
42  R6E      4.0    0.009424
26    R      2.0    0.004712
36   R4      2.0    0.004712
38  R4O      2.0    0.004712
43  R6O      2.0    0.004712
9   C7E      2.0    0.004712
46  R7O      2.0    0.004712
0     C      2.0    0.004712
7   C6E      1.0    0.002356
16    O      1.0    0.002356

In [15]:
import openpyxl
grouped_df.to_excel('일어 전체통계.xlsx', index = False, engine = 'xlsxwriter')